### ISSUE TITLE
Create a high-level roadmap

### ISSUE THREAD

**Issue by Vinnl** [tosdr/phoenix#381]
Trying to get to grips with how I can best contribute to the project, I thought it could be useful to have a high-level roadmap to get a feel for what we're working towards, and what is most important to get the tool to be actually used. I'm writing down what I'm currently guessing that everyone's ideas are, which means I'm likely to get things wrong. In other words: it'd be great if everyone could give their input here :)

For example:

* What is missing?
* What is actually not important
* In what order do we tackle these issues?
* What can be moved to a different milestone
* Which milestones do we need in the first place?
* Which of these are ready and which are not?
* etc.

That'll make it easier to contribute :) If everyone agrees with them we could move this to the wiki or turn it into individual GitHub issues, I guess.

The different roles I'm aware of that users can have are (in my terminology - not sure if there are other words for them):

* Visitor: someone who visits Phoenix but is not signed in
* Contributor: someone who is signed in
* Curator: signed-in team member
 *Admin: ?

So, without further ado, the milestones in order of importance:

# Minimal features needed for the team to use Phoenix for reviewing ToS's

Phoenix *cannot* be used for reviewing terms of service unless it's possible to:

- [X] Add a service as a curator
- [x] Add a case as a curator
- [X] Add a point (=linking a case to a service) as a curator
- [X] Update a service as a curator
- [x] Update a case as a curator
- [x] Update a point as a curator

# Minimal features needed for drive-by contributors to use Phoenix for reviewing ToS's

Phoenix *cannot* be opened to the general public for reviewing terms of service unless it's possible to:

- [X] Sign up for a contributor account as a visitor
- [x] Suggest a point (=linking a case to a service) as a contributor
- [x] Approve/reject suggested points as a curator
- [x] Suggest a case as a contributor (?)
- [x] Approve/reject suggested cases as a curator
- [ ] Suggest a service as a contributor
- [ ] Approve/reject suggested services as a curator
- [ ] See consistent ratings between the current tosdr.org and the Phoenix data as a visitor

# Minimal features needed for Phoenix to manage the display of ratings on tosdr.org

Phoenix *cannot* be used to display ratings on tosdr.org unless it's possible to:

- [X] View grades of services as a visitor
- [X] View points associated with services as a visitor
- [ ] Practically never encounter downtime as a visitor

# Other things we'd like to do

Phoenix is already useful without these, but it would be nicer to use it if it's possible to:

- [x] Create topics as a curator
- [x] Link cases to topics as a curator
- [x] Mark points as "featured" as a curator
- [ ] Add comments on why a suggested case was approved/rejected (especially the latter)
- [ ] Suggest points as "not/no longer relevant" as a contributor
- [ ] Approve "not/no longer relevant" suggestions as a curator
- [ ] Link points to the relevant tosback data as a contributor
- [ ] Automatically have points show up on tosdr.org and in the API, without having to manually run an export script as a curator

**Comment by piks3l** [comment]
> Trying to get to grips with how I can best contribute to the project

great idea !

> - Visitor: someone who visits Phoenix but is not signed in
> - Contributor: someone who is signed in
> - Curator: signed-in team member
> - Admin: ?

With have an admin interface available at `/admin` however I just installed it in case. it just displays the list of users and the connection time but without much features.

# Minimal features needed for the team to use Phoenix for reviewing ToS's

- [x] Add a service as a curator
- [X] Add a case as a curator

Possible :) see `https://edit.tosdr.org/cases/new`

- [x] Add a point (=linking a case to a service) as a curator
- [x] Update a service as a curator
- [ ] Update a case as a curator

Possible :) see `https://edit.tosdr.org/cases/117/edit`

- [x] Update a point as a curator
- [ ] See consistent ratings between the current tosdr.org and the Phoenix data as a visitor
- [ ] Automatically have points show up on tosdr.org and in the API, without having to manually run an export script as a curator

Those are where Michiel is working hard :)

# Minimal features needed for drive-by contributors to use Phoenix for reviewing ToS's

Phoenix **cannot** be opened to the general public for reviewing terms of service unless it's possible to:

- [x] Sign up for a contributor account as a visitor
- [ ] Suggest a point (=linking a case to a service) as a contributor

I'm not entirely sure what you mean here.

- [ ] Approve/reject suggested points as a curator

Already implemented.

- [ ] Suggest a case as a contributor (?)

Already implemented.

- [ ] Approve/reject suggested cases as a curator

Already implemented (but roughly -- no discussion possible, it's just removing something from a list)

# Minimal features needed for Phoenix to manage the display of ratings on tosdr.org

Phoenix **cannot** be used to display ratings on tosdr.org unless it's possible to:

- [x] View grades of services as a visitor
- [x] View points associated with services as a visitor
- [ ] Practically never encounter downtime as a visitor

Thanks to your contribution it is already way better!

# Other things we'd like to do

Phoenix is already useful without these, but it would be nicer to use it if it's possible to:

- [x] Create topics as a curator
- [x] Link cases to topics as a curator
- [x] Mark points as "featured" as a curator
- [ ] Suggest points as "not/no longer relevant" as a contributor
- [ ] Approve "not/no longer relevant" suggestions as a curator
- [ ] Link points to the relevant tosback data as a contributor


Good points! The last one is one of the long-term goals I already discussed with Michiel. 

Generally speaking, I don't mind we work on issues on Gtihub. The milestones haven't been very used because we haven't needed them yet. Though as the group of people involved in the development is growing, I am strongly in favor we organise a bit the way we work so it's easier for every one.

**Comment by michielbdejong** [comment]
> Automatically have points show up on tosdr.org and in the API, without having to manually run an export script as a curator

I would remove that one, at least short-term. I think it's ok as we have it now, manual. That way, I can sanity check everything in case of bugs or misunderstandings. Also, it would be easy enough to make this a daily or hourly cron job when we're ready to do so.

For drive-by contributors, I would add 'add a service'. A lot of people want to add a review for some obscure (or at least non-top-100) site, and even within the top 100, there are enough sites we haven't reviewed yet.

> Phoenix to manage the display of ratings on tosdr.org

what do you mean by that? Is that different from "See consistent ratings between the current tosdr.org and the Phoenix data as a visitor"? Do you mean that phoenix (RoR, hosted at Heroku) should be merged with tosdr.org (statics, hosted at 5apps)?

> Suggest points as "not/no longer relevant"

We can do that by adding a status 'irrelevant', apart from 'pending', 'approved', and 'disputed'.

**Comment by piks3l** [comment]
> For drive-by contributors, I would add 'add a service'. A lot of people want to add a review for some obscure (or at least non-top-100) site, and even within the top 100, there are enough sites we haven't reviewed yet.

Agreed, I missed it yesterday. It is even of the goals of the Beta v0 :)

> We can do that by adding a status 'irrelevant', apart from 'pending', 'approved', and 'disputed'.

Yes !

**Comment by michielbdejong** [comment]
> as the group of people involved in the development is growing, I am strongly in favor we organise a bit the way we work so it's easier for every one.

Agreed! One thing we could do is: if you see something that needs doing, regardless of whether you plan to fix it yourself now, fix it later, or leave it for others to fix, always create a github issue for it.

Whenever someone doesn't know what to work on next, they can look at the list of unassigned github issues. Everybody is free to pick what to work on that excites them, and that they personally feel is urgent right now. To make sure everybody has a good sense of what is urgent, **we should all use phoenix as users, and do some actual reviewing work as often as possible**

When you chose something to work on:
* start by opening a github issue (or find it if it already exists) for the specific thing you want to do.
* assign that github issue to yourself, to show that you are now working on it.
* create a PR that references the issue.
* when the PR is merged, the issue is closed.
* now use the site and do some reviewing, to see if everything works, or if bugs still exist
* repeat for the next issue you encounter! :)

And if you want to make a big change, that may affect things other people are working on, or requires some decision making, describe it in the github issue, and ask others to comment on it, so we reach some consensus before you start working on something others don't fully agree with.

**Comment by piks3l** [comment]
Agreed ! What about adding this to the contribution guide ?

**Comment by michielbdejong** [comment]
I checked a few boxes in @Vinnl's list for things I think are already working.

**Comment by Vinnl** [comment]
I've incorporated your comments into the first post. We can turn it into a wiki page, and then people can create issues when they start to work on them?

What I meant by "Phoenix to manage the display of ratings on tosdr.org" is to replace the static site on tosdr.org by Phoenix, if that's indeed the plan.

**Comment by piks3l** [comment]
> I've incorporated your comments into the first post. We can turn it into a wiki page, and then people can create issues when they start to work on them?

Yes ! And maybe a note about that in the contribution guide ? Thanks !

> What I meant by "Phoenix to manage the display of ratings on tosdr.org" is to replace the static site on tosdr.org by Phoenix, if that's indeed the plan.

It is (at least for me) the plan on the long-term. But we haven't discussed it much with the team. I know @hugoroy is up for it, but no idea about the other neither I have thought about the implementation yet.

**Comment by Vinnl** [comment]
Alright, it's not a near-term milestone anyway, so let's leave it there. I'll move it to the wiki and add it to the contribution guide then.

**Comment by Vinnl** [comment]
Since Phoenix is currently already being used by drive-by contributors and those reviews can actually show up on tosdr.org, I guess we're already pretty much at the end of the current roadmap. Furthermore, there's a bunch of stuff happening w.r.t. annotation and such by Michiel, all of which is not on the roadmap.

In other words: the current roadmap is outdated, which is why I'm deleting it. This is what its contents are at the current point in time, for posterity:

> Here is a high-level roadmap for Phoenix to give contributors some idea of what areas are most in need of contributions. When you start working on (part of) one of these goals, please do create a GitHub issue for it and optionally mention that issue here.
> 
> This roadmap uses the following terminology:
> 
> * Visitor: someone who visits Phoenix but is not signed in
> * Contributor: someone who is signed in
> * Curator: signed-in team member
> 
> So, without further ado, the milestones in order of importance:
> 
> # Minimal features needed for the team to use Phoenix for reviewing ToS's
> 
> Phoenix *cannot* be used for reviewing terms of service unless it's possible to:
> 
> - [X] Add a service as a curator
> - [x] Add a case as a curator
> - [X] Add a point (=linking a case to a service) as a curator
> - [X] Update a service as a curator
> - [x] Update a case as a curator
> - [x] Update a point as a curator
> 
> # Minimal features needed for drive-by contributors to use Phoenix for reviewing ToS's
> 
> Phoenix *cannot* be opened to the general public for reviewing terms of service unless it's possible to:
> 
> - [X] Sign up for a contributor account as a visitor
> - [x] Suggest a point (=linking a case to a service) as a contributor
> - [x] Approve/reject suggested points as a curator
> - [x] Suggest a case as a contributor (?)
> - [x] Approve/reject suggested cases as a curator
> - [x] Suggest a service as a contributor ([#387](https://github.com/tosdr/phoenix/issues/387))
> - [ ] See consistent ratings between the current tosdr.org and the Phoenix data as a visitor
> 
> # Minimal features needed for Phoenix to manage the display of ratings on tosdr.org
> 
> Phoenix *cannot* be used to display ratings on tosdr.org unless it's possible to:
> 
> - [X] View grades of services as a visitor
> - [X] View points associated with services as a visitor
> - [ ] Practically never encounter downtime as a visitor
> 
> # Other things we'd like to do
> 
> Phoenix is already useful without these, but it would be nicer to use it if it's possible to:
> 
> - [x] Create topics as a curator
> - [x] Link cases to topics as a curator
> - [x] Mark points as "featured" as a curator
> - [ ] Add comments on why a suggested case was approved/rejected (especially the latter)
> - [ ] Suggest points as "not/no longer relevant" as a contributor
> - [ ] Approve "not/no longer relevant" suggestions as a curator
> - [ ] Link points to the relevant tosback data as a contributor
> - [ ] Automatically have points show up on tosdr.org and in the API, without having to manually run an export script as a curator
> 
> (This roadmap originated in [#381](https://github.com/tosdr/phoenix/issues/381).)
