### ISSUE TITLE
Some notes as a first time user of the editor site

### ISSUE THREAD

**Issue by petterreinholdtsen** [tosdr/phoenix#482]
I was asked by piks3l[m] to send my comments in as a issue in github, so here it is.

As a first time visitor to <URL: https://edit.tosdr.org/ > is a bitunclear on how to add new services.  It simply state "To review a service's terms and conditions, first make sure the service is listed, and add it if not.", but fail to mention how to add a service.  After logging in and allowing javascript to run, a service search field show up.

After registering and starting to modify a sevice entry, I noticed, it would be great if the html document title (ie the one showing up in my browser history) for <URL: https://edit.tosdr.org/services/514 > mentioned gitlab.  now it just reads "Terms Of Service. Didn't Read - Phoenix".

Visiting <URL: https://edit.tosdr.org/services/514/points/new >, the text mention 'Cases represent recurring aspects of terms of service agreements for different services. For example, "The terms may be changed at any time, without notice to the user."'.  But I am unable to find a case phrased like that.

After registering, I got a email welcoming me to ToS;DR!, where the content of the email is two alternatives, one text/plain and one text/html, and the two do not match.  the html version contain a welcome message, while the plain version do not...

Either the two alternatives should be equivalent, or only one of them should be shipped.

While browsing, I discovered something strange with <URL: https://edit.tosdr.org/services/472 >.  It got an F, but its only info is 'title unknown', and the service is shut down and obsolete...

**Comment by michielbdejong** [comment]
Thanks for reporting this! I'll try to fix these issues in the coming days:

* [ ] #485 unclear how to add new services
* [ ] #486 html document titles
* [ ] #487 searching for a case
* [ ] #488 signup email text/html versions don't match
* [ ] #489 bug in service rating displayed?

**Comment by michielbdejong** [comment]
Thanks @petterreinholdtsen for reporting those! I fixed all except #487, so please see that issue for further follow-ups. Discussion continued there! :)
